#!/usr/bin/env bash
set -euo pipefail

os="$(uname -s)"
arch="$(uname -m)"

export MAGIC_NIX_CACHE_LISTEN="127.0.0.1:37515"

case "${os}" in
  Linux)
    export DETERMINATE_NIX_INSTALL_URL="https://install.determinate.systems/nix?ci=buildkite"
    nix_profile_path="/root/.nix-profile/bin"

    case "${arch}" in
      x86_64)  closure_arch="X64-Linux" nix_system="x86_64-linux" ;;
      aarch64) closure_arch="ARM64-Linux" nix_system="aarch64-linux" ;;
      *) echo "Unsupported Linux architecture: ${arch}"; exit 1 ;;
    esac

    ;;
  Darwin)
    export DETERMINATE_NIX_INSTALL_URL="https://install.determinate.systems/determinate-pkg/stable/Universal"
    nix_profile_path="/nix/var/nix/profiles/default/bin"

    case "${arch}" in
      arm64)  closure_arch="ARM64-macOS" nix_system="aarch64-darwin" ;;
      *) echo "Unsupported macOS architecture: ${arch}"; exit 1 ;;
    esac
    ;;
  *)
    echo "Unsupported OS: ${os}"
    exit 1
    ;;
esac

export MAGIC_NIX_CACHE_CLOSURE_URL="https://github.com/DeterminateSystems/magic-nix-cache/releases/latest/download/magic-nix-cache-${closure_arch}"

curl \
  --output "determinate-nixd" \
  --proto '=https' \
  --tlsv1.2 -sSf -L \
  "https://install.determinate.systems/determinate-nixd/rev/7a5fd0a417f3a25e784f5758a0fcdc7d4ea7570e/${nix_system}"
chmod +x determinate-nixd

if ! determinate-nixd version &>/dev/null; then
  echo "Installing Determinate Nix"

  case "${os}" in
    Linux)
      curl --proto '=https' --tlsv1.2 -sSf -L "${DETERMINATE_NIX_INSTALL_URL}" | \
        sh -s -- install linux \
          --no-confirm \
          --init none

      sudo mv -f ./determinate-nixd /usr/local/bin/determinate-nixd
      sudo nohup /usr/local/bin/determinate-nixd daemon &
      export NIX_REMOTE="daemon"
      ;;
    Darwin)
      curl --proto '=https' --tlsv1.2 -sSf -L "${DETERMINATE_NIX_INSTALL_URL}" -o /tmp/Determinate.pkg
      sudo installer -pkg /tmp/Determinate.pkg -target /
      mv ./determinate-nixd /usr/local/bin/determinate-nixd
      ;;
  esac

  echo "Waiting for Determinate Nixd status..."

  while ! determinate-nixd status &>/dev/null; do
    sleep 0.1;
  done

  echo "Determinate Nix installed"
else
  echo "Determinate Nix detected, skipping install"
fi

# Set PATH to include Nix-created directories
PATH="${PATH}:${nix_profile_path}"

echo "Logging in to FlakeHub using OIDC token"

determinate-nixd auth login buildkite || true

# Try to kill any lingering magic-nix-cache processes
nix shell nixpkgs#toybox -c killall -s SIGKILL magic-nix-cache || true

if ! command -v magic-nix-cache &>/dev/null; then
  echo "Installing Magic Nix Cache"

  mnc_closure="$(curl -L "${MAGIC_NIX_CACHE_CLOSURE_URL}" |
    xz -d |
    sudo "$(which nix-store)" --import |
    tail -n1 |
    head -n1
  )"
  PATH="${PATH}:/usr/local/bin"
  sudo mkdir -p /usr/local/bin
  sudo ln -sf "${mnc_closure}/bin/magic-nix-cache" /usr/local/bin/magic-nix-cache

  echo "Magic Nix Cache installed"
else
  echo "Magic Nix Cache detected, skipping install"
fi

mnc_log_file="/tmp/mnc-${BUILDKITE_JOB_ID}.log"
mnc_startup_file=/tmp/mnc-startup-"${BUILDKITE_JOB_ID}"

case "${os}" in
  Linux)
    nohup magic-nix-cache --listen "${MAGIC_NIX_CACHE_LISTEN}" \
      --startup-notification-file "${mnc_startup_file}" \
      &> "${mnc_log_file}" &
    ;;
  Darwin)
    nix run nixpkgs#tmux -- new -d -s mnc \
      "magic-nix-cache --listen ${MAGIC_NIX_CACHE_LISTEN} \
        --startup-notification-file ${mnc_startup_file}" \
      \; pipe-pane -t mnc "cat > ${mnc_log_file}"
    ;;
esac
(
  echo "Waiting for Magic Nix Cache to start up..."
  started=0
  for n in {1..30}; do
    if [ -e "${mnc_startup_file}" ]; then
      echo "Magic Nix Cache daemon has successfully started up after ${n} attempt(s)"
      started=1
      break
    else
      echo "Waiting on Magic Nix Cache daemon; on attempt ${n}"
      sleep 2
    fi
  done

  if [[ "${started}" != "1" ]]; then
    echo "The Magic Nix Cache daemon did not start up within 60 seconds; exiting"
    exit 1
  fi
)
